Docs zh
webpack/tapable pull request #154
Opened 2021-01-29 07:11 UTC by xiaoxiaocoder

2021-03-09 10:16 UTC, roadupcc requested changes

2021-03-09 10:16 UTC, roadupcc commented on README-zh.md
> +在你的拆件中, Hook 会被编译成最有效的执行方式. 编译逻辑(用于生成执行代码)取决于:
```suggestion
在你的插件中, Hook 会被编译成最有效的执行方式. 编译逻辑(用于生成执行代码)取决于:
```

2021-03-09 10:16 UTC, roadupcc commented on README-zh.md
> +A helper Hook-like class to redirect taps to multiple other hooks:
```suggestion
一个类似Hook的类的助手用来tap到其他的多个Hook:
```

2025-05-16 16:47 UTC, alexander-akait commented
Sorry we support only English documentation, you can create own repo/fork and put it here

2025-05-16 16:47 UTC, closed without merging